/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Login.Login;
import datos.DatosSucursal;
import datos.DatosUsuario;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;


public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
   
    public Principal() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("../Imagenes/logochiquito.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
              setIconImage(new ImageIcon(getClass().getResource("probar.png")).getImage());
        this.setLocationRelativeTo(this);
        this.uno.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
         /*datos.DatosSucursal xn = new DatosSucursal();
        int obtenersuc=xn.ObtenerSucursal(Integer.parseInt(Sucursal_ID.getText().trim()));
        Sucursal_ID.setText(Sucursal_ID.getText().trim());*/
         
         Date datoObj = new Date();
         
         fecha.setText(LocalDate.now().toString());
        
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        status_Caja = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Sucursal_ID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Sucursal_ID1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        uno = new rsbuttom.RSButtonMetro();
        tres = new rsbuttom.RSButtonMetro();
        dos = new rsbuttom.RSButtonMetro();
        cinco = new rsbuttom.RSButtonMetro();
        ocho = new rsbuttom.RSButtonMetro();
        siete = new rsbuttom.RSButtonMetro();
        cuatro = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery App");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2585, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(2585, 700));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Menu+.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Menu+.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Menu+.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Menu+.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nombre_loc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        nombre_loc.setForeground(new java.awt.Color(255, 255, 255));
        nombre_loc.setText("Delivery");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/calendario(1).png"))); // NOI18N

        fecha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 102, 255));
        fecha.setText("08/12/2020");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/pin-de-ubicacion.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Santiago del Estero, Capital");

        bienvenido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido, ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/bienvenido(1).png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status de Caja: ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/cajero.png"))); // NOI18N

        status_Caja.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        status_Caja.setForeground(new java.awt.Color(255, 51, 51));
        status_Caja.setText("Cerrada");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/caja-de-pizza(1).png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sucursal N°:");

        Sucursal_ID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        Sucursal_ID.setForeground(new java.awt.Color(102, 255, 102));
        Sucursal_ID.setText("1");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre de Sucursal:");

        Sucursal_ID1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        Sucursal_ID1.setForeground(new java.awt.Color(102, 255, 102));
        Sucursal_ID1.setText("Delivery de joaco");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/caja-de-pizza(1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bienvenido)
                .addGap(2, 2, 2)
                .addComponent(nombre_loc)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status_Caja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addComponent(Sucursal_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addComponent(Sucursal_ID1)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bienvenido)
                                .addComponent(nombre_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(status_Caja))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(Sucursal_ID))
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(Sucursal_ID1))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentro.setMaximumSize(new java.awt.Dimension(2585, 700));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(2585, 700));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        pnlMenu.setBackground(new java.awt.Color(153, 153, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(2585, 700));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setBackground(new java.awt.Color(153, 153, 255));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Home_ico.png"))); // NOI18N
        uno.setText("Inicio");
        uno.setColorHover(new java.awt.Color(51, 51, 51));
        uno.setColorNormal(new java.awt.Color(153, 153, 255));
        uno.setColorPressed(new java.awt.Color(51, 51, 51));
        uno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno.setIconTextGap(25);
        uno.setMargin(new java.awt.Insets(2, 14, 2, 29));
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        pnlMenu.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 52));

        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cadete_ico.png"))); // NOI18N
        tres.setText("Cadetes");
        tres.setColorHover(new java.awt.Color(51, 51, 51));
        tres.setColorNormal(new java.awt.Color(153, 153, 255));
        tres.setColorPressed(new java.awt.Color(51, 51, 51));
        tres.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres.setIconTextGap(19);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        pnlMenu.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));

        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Pedidos_ico.png"))); // NOI18N
        dos.setText("Pedidos");
        dos.setAlignmentX(0.2F);
        dos.setColorHover(new java.awt.Color(51, 51, 51));
        dos.setColorNormal(new java.awt.Color(153, 153, 255));
        dos.setColorPressed(new java.awt.Color(51, 51, 51));
        dos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos.setIconTextGap(25);
        dos.setMargin(new java.awt.Insets(2, 14, 2, 29));
        dos.setMaximumSize(new java.awt.Dimension(97, 31));
        dos.setMinimumSize(new java.awt.Dimension(97, 31));
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        pnlMenu.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 50));

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Chef_ico.png"))); // NOI18N
        cinco.setText("Comidas");
        cinco.setColorHover(new java.awt.Color(51, 51, 51));
        cinco.setColorNormal(new java.awt.Color(153, 153, 255));
        cinco.setColorPressed(new java.awt.Color(51, 51, 51));
        cinco.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco.setIconTextGap(19);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        pnlMenu.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Salir_ico.png"))); // NOI18N
        ocho.setText("Cerrar ");
        ocho.setColorHover(new java.awt.Color(51, 51, 51));
        ocho.setColorNormal(new java.awt.Color(153, 153, 255));
        ocho.setColorPressed(new java.awt.Color(51, 51, 51));
        ocho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ocho.setIconTextGap(19);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        pnlMenu.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 50));

        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Estadisticas_ico.png"))); // NOI18N
        siete.setText("Graficas");
        siete.setColorHover(new java.awt.Color(51, 51, 51));
        siete.setColorNormal(new java.awt.Color(153, 153, 255));
        siete.setColorPressed(new java.awt.Color(51, 51, 51));
        siete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        siete.setIconTextGap(19);
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sieteMousePressed(evt);
            }
        });
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        pnlMenu.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 50));

        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cliente_ico.png"))); // NOI18N
        cuatro.setText("Clientes");
        cuatro.setColorHover(new java.awt.Color(51, 51, 51));
        cuatro.setColorNormal(new java.awt.Color(153, 153, 255));
        cuatro.setColorPressed(new java.awt.Color(51, 51, 51));
        cuatro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro.setIconTextGap(19);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        pnlMenu.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 50));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("® DeliveryApp - 2020 - Version 1.0 ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pnlMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 250, 70));

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentroLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
            //Animacion.Animacion.mover_izquierda(200, 0, 2, 2, jButton1);
            Animacion.Animacion.mover_izquierda(0, -100, 2, 2, pnlCentro);
            
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
           // Animacion.Animacion.mover_derecha(0, 200, 2, 2, jButton1);
             Animacion.Animacion.mover_derecha(0, 0, 2, 2, pnlCentro);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlFeeBack());
        if(this.cuatro.isSelected()){
            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

          //  this.seis.setColorNormal(new Color(153,153,255));
           // this.seis.setColorHover(new Color(51,51,51));
           // this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);
        this.cinco.setSelected(false);
        //this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cuatroMousePressed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlIOS());
        if(this.siete.isSelected()){
            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

          //  this.seis.setColorNormal(new Color(153,153,255));
           // this.seis.setColorHover(new Color(51,51,51));
           // this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void sieteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
      //  this.seis.setSelected(false);
        this.siete.setSelected(true);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_sieteMousePressed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        
        Login x = new Login();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_ochoActionPerformed

    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
      //  this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(true);
    }//GEN-LAST:event_ochoMousePressed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlMarket());
        if(this.cinco.isSelected()){
            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

//            this.seis.setColorNormal(new Color(153,153,255));
           // this.seis.setColorHover(new Color(51,51,51));
       //     this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(true);
//        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cincoMousePressed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlCollection());
        if(this.dos.isSelected()){

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

//            this.seis.setColorNormal(new Color(153,153,255));
        //    this.seis.setColorHover(new Color(51,51,51));
      //      this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_dosActionPerformed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
//        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_dosMousePressed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlChat());
        if(this.tres.isSelected()){
            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

      //      this.seis.setColorNormal(new Color(153,153,255));
     //       this.seis.setColorHover(new Color(51,51,51));
       //     this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_tresActionPerformed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(true);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
     //   this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_tresMousePressed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
        if(this.uno.isSelected()){
            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));

            this.dos.setColorNormal(new Color(153,153,255));
            this.dos.setColorHover(new Color(51,51,51));
            this.dos.setColorPressed(new Color(51,51,51));

            this.tres.setColorNormal(new Color(153,153,255));
            this.tres.setColorHover(new Color(51,51,51));
            this.tres.setColorPressed(new Color(51,51,51));

            this.cuatro.setColorNormal(new Color(153,153,255));
            this.cuatro.setColorHover(new Color(51,51,51));
            this.cuatro.setColorPressed(new Color(51,51,51));

            this.cinco.setColorNormal(new Color(153,153,255));
            this.cinco.setColorHover(new Color(51,51,51));
            this.cinco.setColorPressed(new Color(51,51,51));

         //   this.seis.setColorNormal(new Color(153,153,255));
         //   this.seis.setColorHover(new Color(51,51,51));
          //  this.seis.setColorPressed(new Color(51,51,51));

            this.siete.setColorNormal(new Color(153,153,255));
            this.siete.setColorHover(new Color(51,51,51));
            this.siete.setColorPressed(new Color(51,51,51));

            this.ocho.setColorNormal(new Color(153,153,255));
            this.ocho.setColorHover(new Color(51,51,51));
            this.ocho.setColorPressed(new Color(51,51,51));
        }else{
            this.uno.setColorNormal(new Color(153,153,255));
            this.uno.setColorHover(new Color(51,51,51));
            this.uno.setColorPressed(new Color(51,51,51));
        }
    }//GEN-LAST:event_unoActionPerformed

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        this.uno.setSelected(true);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
//        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_unoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                     
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Sucursal_ID;
    public static javax.swing.JLabel Sucursal_ID1;
    public javax.swing.JLabel bienvenido;
    private rsbuttom.RSButtonMetro cinco;
    private rsbuttom.RSButtonMetro cuatro;
    private rsbuttom.RSButtonMetro dos;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JLabel nombre_loc = new javax.swing.JLabel();
    private rsbuttom.RSButtonMetro ocho;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro siete;
    public static javax.swing.JLabel status_Caja;
    private rsbuttom.RSButtonMetro tres;
    private rsbuttom.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables
}
