/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import controladores.ControlLogin;
import datos.DatosSucursal;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import principal.Principal;
import paneles.*;

/**
 *
 * @author alex1
 */
public class Login extends javax.swing.JFrame {
    
   
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
       setIconImage(new ImageIcon(getClass().getResource("probar.png")).getImage());
      
         //Usuario_lbl.setFont(new Font("IBM Plex Sans ExtraLight",Font.PLAIN,22));
         //Contrasena_lbl.setFont(new Font("IBM Plex Sans ExtraLight",Font.PLAIN,22));
         Crear_Cuenta.setFont(new Font("IBM Plex Sans ExtraLight",Font.PLAIN,12));
       
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Imagen_Derecha = new javax.swing.JLabel();
        Imagen_Login = new javax.swing.JLabel();
        Cerrar_btn = new necesario.MaterialButton();
        Entrar_btn = new necesario.MaterialButton();
        pass_tfld = new rojeru_san.RSMPassView();
        Usuario_tfld = new RSMaterialComponent.RSTextFieldTwo();
        Copy_jlb = new javax.swing.JLabel();
        Crear_Cuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Olvide_pass_jlb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imgprincipal.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        Imagen_Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliveryapp/Imagenes/pexels-norma-mortenson-4393444.jpg"))); // NOI18N
        jPanel1.add(Imagen_Derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 640, 630));

        Imagen_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliveryapp/Imagenes/Imagen-Login.png"))); // NOI18N
        jPanel1.add(Imagen_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        Cerrar_btn.setBackground(new java.awt.Color(153, 153, 255));
        Cerrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar_btn.setText("Cerrar");
        Cerrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 220, 50));

        Entrar_btn.setBackground(new java.awt.Color(51, 51, 51));
        Entrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn.setText("Entrar");
        Entrar_btn.setContentAreaFilled(false);
        Entrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 80, 50));

        pass_tfld.setForeground(new java.awt.Color(51, 51, 51));
        pass_tfld.setBordeColorFocus(new java.awt.Color(153, 153, 153));
        pass_tfld.setBotonColor(new java.awt.Color(204, 255, 204));
        pass_tfld.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pass_tfld.setPlaceholder("                   Contraseña ");
        pass_tfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_tfldActionPerformed(evt);
            }
        });
        jPanel1.add(pass_tfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, -1));

        Usuario_tfld.setForeground(new java.awt.Color(51, 51, 51));
        Usuario_tfld.setBorderColor(new java.awt.Color(153, 153, 153));
        Usuario_tfld.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Usuario_tfld.setPhColor(new java.awt.Color(109, 109, 109));
        Usuario_tfld.setPlaceholder("                      Usuario");
        Usuario_tfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_tfldActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario_tfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 280, -1));

        Copy_jlb.setForeground(new java.awt.Color(153, 153, 153));
        Copy_jlb.setText("® 2020- DeliveryApp");
        jPanel1.add(Copy_jlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 130, 20));

        Crear_Cuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Crear_Cuenta.setForeground(new java.awt.Color(102, 102, 255));
        Crear_Cuenta.setText("Crear cuenta nueva");
        Crear_Cuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Crear_Cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Crear_CuentaMouseClicked(evt);
            }
        });
        jPanel1.add(Crear_Cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contrasena-incorrecta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 40, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-protection(1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 50, -1));

        Olvide_pass_jlb1.setForeground(new java.awt.Color(102, 102, 255));
        Olvide_pass_jlb1.setText("Olvide la contraseña");
        Olvide_pass_jlb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Olvide_pass_jlb1MouseClicked(evt);
            }
        });
        jPanel1.add(Olvide_pass_jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 120, 30));

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btnActionPerformed
    ControlLogin x = new ControlLogin();
        try {
            x.iniciarSesion(this);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Entrar_btnActionPerformed

    private void Cerrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_btnActionPerformed
   
        
    }//GEN-LAST:event_Cerrar_btnActionPerformed

    private void Usuario_tfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_tfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_tfldActionPerformed

    private void Crear_CuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crear_CuentaMouseClicked
       Pregunta_Admin x = new Pregunta_Admin() ; 
       x.setVisible(true);
       dispose();
    }//GEN-LAST:event_Crear_CuentaMouseClicked

    private void pass_tfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_tfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfldActionPerformed

    private void Olvide_pass_jlb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Olvide_pass_jlb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Olvide_pass_jlb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.MaterialButton Cerrar_btn;
    private javax.swing.JLabel Copy_jlb;
    private javax.swing.JLabel Crear_Cuenta;
    private necesario.MaterialButton Entrar_btn;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Imagen_Derecha;
    private javax.swing.JLabel Imagen_Login;
    private javax.swing.JLabel Olvide_pass_jlb1;
    public RSMaterialComponent.RSTextFieldTwo Usuario_tfld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public rojeru_san.RSMPassView pass_tfld;
    // End of variables declaration//GEN-END:variables
}
