/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPaneles;

import Login.*;
import controladores.ControlCadete;
import controladores.ControlCaja;
import controladores.ControlComida;
import controladores.ControlPedido;
import datos.DatosComida;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import paneles.pnlHome;
import principal.Principal;

/**
 *
 * @author alex1
 */
public class Registro_Pedido_Nuevo_otro extends javax.swing.JFrame {
  
    int contador=5;
    public DefaultTableModel model ;
      
       
    /**
     * Creates new form Registro_Login
     */
    public Registro_Pedido_Nuevo_otro() {
        initComponents();
        this.setLocationRelativeTo(this);
          setIconImage(new ImageIcon(getClass().getResource("probar.png")).getImage());
          ControlComida ff = new ControlComida();
           
            model= new DefaultTableModel();
             model.addColumn("Id Comida");
             model.addColumn("Nombre");
             model.addColumn("Cantidad");
             model.addColumn("Precio");
        try {
            ff.obtenercomida();
            ff.obtenerBebida();
            ff.obtenerPostre();
            ff.obtenerzona();
            ff.obtenercadetes();
           
           
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
        }
    
          
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresar_DirA_P = new RSMaterialComponent.RSTextFieldMaterial();
        Domicilio_RP = new RSMaterialComponent.RSTextFieldMaterial();
        Ingrese_telefono_NP = new RSMaterialComponent.RSTextFieldMaterial();
        Entrar_btn = new necesario.MaterialButton();
        jLabel2 = new javax.swing.JLabel();
        Entrar_btn1 = new necesario.MaterialButton();
        Nombre_RP = new RSMaterialComponent.RSTextFieldMaterial();
        jPanel2 = new javax.swing.JPanel();
        ingresar_Estado_P2 = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Cadete_P = new RSMaterialComponent.RSComboBoxMaterial();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        jLabel6 = new javax.swing.JLabel();
        Final_Precio_P = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ingresar_HD_P = new RSMaterialComponent.RSTextFieldMaterial();
        ingresar_HR_P = new RSMaterialComponent.RSTextFieldMaterial();
        cliente_No_Exite_RP = new javax.swing.JLabel();
        Apellido_RP1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel10 = new javax.swing.JLabel();
        ingresar_DirA_P1 = new RSMaterialComponent.RSTextFieldMaterial();
        recuperarfecha2 = new newscomponents.RSDateChooserModern();
        recuperarfecha = new newscomponents.RSDateChooserModern();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ingresar_Comida_Cant = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Comida = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel7 = new javax.swing.JLabel();
        ingresar_Bebida = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Bebida_Cant = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel30 = new javax.swing.JLabel();
        ingresar_Postre = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Postre_Cant = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladecomida = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Final_Precio_P1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel34 = new javax.swing.JLabel();
        ingresar_Zona = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1242, 562));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/Registro_Pedidos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, -1, 50));

        ingresar_DirA_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_DirA_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_DirA_P.setPlaceholder("Ingrese Dir. A dejar Pedido");
        jPanel1.add(ingresar_DirA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 170, 40));

        Domicilio_RP.setBackground(new java.awt.Color(102, 102, 102));
        Domicilio_RP.setForeground(new java.awt.Color(255, 255, 255));
        Domicilio_RP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Domicilio_RP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Domicilio_RP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Domicilio_RP.setPhColor(new java.awt.Color(0, 0, 0));
        Domicilio_RP.setPlaceholder("");
        jPanel1.add(Domicilio_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 40));

        Ingrese_telefono_NP.setForeground(new java.awt.Color(51, 51, 51));
        Ingrese_telefono_NP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Ingrese_telefono_NP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Ingrese_telefono_NP.setPhColor(new java.awt.Color(0, 0, 0));
        Ingrese_telefono_NP.setPlaceholder("Ingrese Telefono");
        Ingrese_telefono_NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingrese_telefono_NPActionPerformed(evt);
            }
        });
        jPanel1.add(Ingrese_telefono_NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 104, 130, -1));

        Entrar_btn.setBackground(new java.awt.Color(102, 102, 102));
        Entrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn.setText("Volver");
        Entrar_btn.setContentAreaFilled(false);
        Entrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 232, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/flecha-correcta.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 50));

        Entrar_btn1.setBackground(new java.awt.Color(102, 102, 255));
        Entrar_btn1.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn1.setText("Registrar");
        Entrar_btn1.setContentAreaFilled(false);
        Entrar_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 232, 50));

        Nombre_RP.setBackground(new java.awt.Color(102, 102, 102));
        Nombre_RP.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_RP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre_RP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Nombre_RP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Nombre_RP.setPhColor(new java.awt.Color(0, 0, 0));
        Nombre_RP.setPlaceholder("");
        jPanel1.add(Nombre_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 81, -1, -1));

        ingresar_Estado_P2.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Estado_P2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Activo", "En Preparacion" }));
        ingresar_Estado_P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Estado_P2ActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Estado_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 150, 43));

        ingresar_Cadete_P.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Cadete_P.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cadete" }));
        jPanel1.add(ingresar_Cadete_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 150, 43));

        rSButtonMaterialTwo3.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMaterialTwo3.setText("Buscar");
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Final");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));

        Final_Precio_P.setForeground(new java.awt.Color(51, 51, 51));
        Final_Precio_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        Final_Precio_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Final_Precio_P.setPhColor(new java.awt.Color(0, 0, 0));
        Final_Precio_P.setPlaceholder("$");
        jPanel1.add(Final_Precio_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 220, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/Cuadrado4.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 180, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/lupa.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("+");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        ingresar_HD_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_HD_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_HD_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_HD_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_HD_P.setPlaceholder("Hora D.");
        ingresar_HD_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_HD_PActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_HD_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 140, 40));

        ingresar_HR_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_HR_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_HR_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_HR_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_HR_P.setPlaceholder("Hora R.");
        jPanel1.add(ingresar_HR_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 150, 40));
        jPanel1.add(cliente_No_Exite_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        Apellido_RP1.setBackground(new java.awt.Color(102, 102, 102));
        Apellido_RP1.setForeground(new java.awt.Color(255, 255, 255));
        Apellido_RP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Apellido_RP1.setColorMaterial(new java.awt.Color(153, 102, 255));
        Apellido_RP1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Apellido_RP1.setPhColor(new java.awt.Color(0, 0, 0));
        Apellido_RP1.setPlaceholder("");
        Apellido_RP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido_RP1ActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido_RP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Dir. Dejar Pedido");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        ingresar_DirA_P1.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P1.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_DirA_P1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P1.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_DirA_P1.setPlaceholder("Ingrese Dir. A Retirar");
        jPanel1.add(ingresar_DirA_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 170, 40));

        recuperarfecha2.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.add(recuperarfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 170, 40));

        recuperarfecha.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.add(recuperarfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cuadrado2.png"))); // NOI18N
        jLabel11.setText("Detalle de Pedido");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 1, 130));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Dir. Dejar Pedido");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Hora para Retiro de ped.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Dir. Dejar Pedido");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Dir. Dejar Retirar Pedido");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Hora para Dejar");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Detalle de Pedido");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("    Domicilio");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 90, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cuadrado2.png"))); // NOI18N
        jLabel18.setText("Detalle de Pedido");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 1, 170));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Apellido");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 60, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/flecha-hacia-arriba.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 60, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cuadrado2.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 270));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Cuadrado2.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 110));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 255));
        jLabel23.setText("Detalles de Cliente");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/caja-de-entrega.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Añada un numero de telefono");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 255));
        jLabel27.setText("Antes de continuar.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Listado de comida del pedido");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Añadir Comida De Pedido");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("*Se pondra el valor de la zona a la que se lleva el Ped.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 20));

        Ingresar_Comida_Cant.setForeground(new java.awt.Color(102, 102, 102));
        Ingresar_Comida_Cant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        Ingresar_Comida_Cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_Comida_CantActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar_Comida_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 60, 43));

        ingresar_Comida.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Comida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una Comida" }));
        ingresar_Comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_ComidaActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, 40));

        ingresar_Bebida.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Bebida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una bebida" }));
        ingresar_Bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_BebidaActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 43));

        ingresar_Bebida_Cant.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Bebida_Cant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        ingresar_Bebida_Cant.setVerifyInputWhenFocusTarget(false);
        ingresar_Bebida_Cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Bebida_CantActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Bebida_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 60, 43));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, 40));

        ingresar_Postre.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Postre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un postre" }));
        ingresar_Postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_PostreActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 180, 43));

        ingresar_Postre_Cant.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Postre_Cant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        ingresar_Postre_Cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Postre_CantActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Postre_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 60, 43));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, 40));

        tabladecomida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDComida", "Nombre", "Cant", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tabladecomida);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 400, 130));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Cadete");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 90, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 153, 153));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/Cuadrado4.png"))); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 110, 50));

        Final_Precio_P1.setBackground(new java.awt.Color(0, 0, 0));
        Final_Precio_P1.setForeground(new java.awt.Color(255, 255, 255));
        Final_Precio_P1.setCaretColor(new java.awt.Color(255, 255, 255));
        Final_Precio_P1.setColorMaterial(new java.awt.Color(153, 255, 153));
        Final_Precio_P1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Final_Precio_P1.setPhColor(new java.awt.Color(255, 255, 255));
        Final_Precio_P1.setPlaceholder("$");
        jPanel1.add(Final_Precio_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 130, 50));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Precio Final");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, -1));

        ingresar_Zona.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Zona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Zona" }));
        jPanel1.add(ingresar_Zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 150, 43));

        jLabel35.setForeground(new java.awt.Color(102, 51, 0));
        jLabel35.setText("*Recuerde que un porcentaje del precio final ira destinado al cadete.");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, 20));

        jButton1.setText("Añadir Cadete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, -1, -1));

        jButton2.setText("Añadir a Precio Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    
    
    private void Entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btnActionPerformed
         ControlCaja c= new ControlCaja();
            ControlPedido t = new ControlPedido();
               try {
            t.actualizarTablaPedidos3();
            c.obtenerMontocajaF();
        } catch (SQLException ex) {
            Logger.getLogger(pnlHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_Entrar_btnActionPerformed

    private void Entrar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btn1ActionPerformed
ControlPedido cc = new ControlPedido();
        try {
            cc.insertarPedidoPrueba(this);
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Entrar_btn1ActionPerformed

    private void ingresar_Estado_P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Estado_P2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Estado_P2ActionPerformed

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
        ControlPedido VerCli = new ControlPedido();
          VerCli.ValidarClientePNUEVO_prueba(this);
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed

    private void Ingrese_telefono_NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingrese_telefono_NPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingrese_telefono_NPActionPerformed

    private void ingresar_HD_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_HD_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_HD_PActionPerformed

    private void Apellido_RP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido_RP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido_RP1ActionPerformed

    private void Ingresar_Comida_CantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_Comida_CantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_Comida_CantActionPerformed

    private void ingresar_ComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_ComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_ComidaActionPerformed

    private void ingresar_BebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_BebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_BebidaActionPerformed

    private void ingresar_Bebida_CantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Bebida_CantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Bebida_CantActionPerformed

    private void ingresar_PostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_PostreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_PostreActionPerformed

    private void ingresar_Postre_CantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Postre_CantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Postre_CantActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
ControlComida cs = new ControlComida();

      
    try {
        cs.actualizarTablaComida(this);
    } catch (SQLException ex) {
        Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
    }
  
      
            
          
           
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
ControlComida cs = new ControlComida();

      
    try {
        cs.actualizarTablaComida2(this);
    } catch (SQLException ex) {
        Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
    }
  
      
          
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
    ControlComida cs = new ControlComida();

      
    try {
        cs.actualizarTablaComida3(this);
    } catch (SQLException ex) {
        Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ControlCadete rr = new ControlCadete();
        try {
            rr.obtenercadetes3();
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       obtenerpreciofinal();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void obtenerpreciofinal(){
    
        //anda bien el contador
        
    int contadorP=tabladecomida.getRowCount();
    int i = 0;
     String cantidad = "";
    float PrecioTotal = 0 ;
    String Precio="";
    String precioCadete="";
    Float precioC=null;
    while(i<contadorP){
                Precio = tabladecomida.getValueAt(i, 3).toString();
                cantidad = tabladecomida.getValueAt(i, 2).toString();

                float pre = Float.parseFloat(Precio);

                int cant = Integer.parseInt(cantidad);

                PrecioTotal = PrecioTotal+(pre * cant);
    
        i++;
    }
    
    precioCadete=Final_Precio_P1.getText().toString();
    precioC=Float.parseFloat(precioCadete);
    PrecioTotal=PrecioTotal+precioC;
    Final_Precio_P.setText(Float.toString(PrecioTotal));
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo_otro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Pedido_Nuevo_otro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTextFieldMaterial Apellido_RP1;
    public RSMaterialComponent.RSTextFieldMaterial Domicilio_RP;
    private necesario.MaterialButton Entrar_btn;
    private necesario.MaterialButton Entrar_btn1;
    public RSMaterialComponent.RSTextFieldMaterial Final_Precio_P;
    public static RSMaterialComponent.RSTextFieldMaterial Final_Precio_P1;
    public static RSMaterialComponent.RSComboBoxMaterial Ingresar_Comida_Cant;
    public RSMaterialComponent.RSTextFieldMaterial Ingrese_telefono_NP;
    public RSMaterialComponent.RSTextFieldMaterial Nombre_RP;
    public static javax.swing.JLabel cliente_No_Exite_RP;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Bebida;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Bebida_Cant;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Cadete_P;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Comida;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_DirA_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_DirA_P1;
    public RSMaterialComponent.RSComboBoxMaterial ingresar_Estado_P2;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_HD_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_HR_P;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Postre;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Postre_Cant;
    public static RSMaterialComponent.RSComboBoxMaterial ingresar_Zona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    public newscomponents.RSDateChooserModern recuperarfecha;
    public static newscomponents.RSDateChooserModern recuperarfecha2;
    public static javax.swing.JTable tabladecomida;
    // End of variables declaration//GEN-END:variables
}
