/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPaneles;

import Login.*;
import controladores.ControlPedido;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import principal.Principal;

/**
 *
 * @author alex1
 */
public class Registro_Pedido_Nuevo extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Login
     */
    public Registro_Pedido_Nuevo() {
        initComponents();
        this.setLocationRelativeTo(this);
          setIconImage(new ImageIcon(getClass().getResource("probar.png")).getImage());
        
        
        DirDejarPed.setVisible(false);
        DirRetorarped.setVisible(false);
        EstadoPed.setVisible(false);
        SeleccionarCadete.setVisible(false);
        Mas.setVisible(false);
        menos.setVisible(false);
        
       
        DirDejarPed1.setVisible(false);
        DirRetorarped1.setVisible(false);
        EstadoPed1.setVisible(false);
        SeleccionarCadete1.setVisible(false);
        Mas1.setVisible(false);
        menos1.setVisible(false);
        
       
        DirDejarPed2.setVisible(false);
        DirRetorarped2.setVisible(false);
        EstadoPed2.setVisible(false);
        SeleccionarCadete2.setVisible(false);
        //Mas2.setVisible(false);
        menos2.setVisible(false);
        
        DirRetorarped13.setVisible(false);
        DirRetorarped14.setVisible(false);
        DirRetorarped16.setVisible(false);
        DirRetorarped17.setVisible(false);
        DirRetorarped18.setVisible(false);
        DirRetorarped.setVisible(false);
        DirRetorarped5.setVisible(false);
        DirRetorarped6.setVisible(false);
        DirRetorarped7.setVisible(false);
        DirRetorarped8.setVisible(false);
        DirRetorarped9.setVisible(false);
        DirRetorarped10.setVisible(false);
        DirRetorarped11.setVisible(false);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresar_DirR_P = new RSMaterialComponent.RSTextFieldMaterial();
        ingresar_DirA_P = new RSMaterialComponent.RSTextFieldMaterial();
        Domicilio_RP = new RSMaterialComponent.RSTextFieldMaterial();
        Ingrese_telefono_NP = new RSMaterialComponent.RSTextFieldMaterial();
        Entrar_btn = new necesario.MaterialButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Entrar_btn1 = new necesario.MaterialButton();
        Nombre_RP = new RSMaterialComponent.RSTextFieldMaterial();
        jPanel2 = new javax.swing.JPanel();
        DirRetorarped = new RSMaterialComponent.RSTextFieldMaterial();
        DirDejarPed = new RSMaterialComponent.RSTextFieldMaterial();
        menos = new javax.swing.JLabel();
        Mas = new javax.swing.JLabel();
        EstadoPed = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Estado_P = new RSMaterialComponent.RSComboBoxMaterial();
        SeleccionarCadete = new RSMaterialComponent.RSComboBoxMaterial();
        ingresar_Cadete_P = new RSMaterialComponent.RSComboBoxMaterial();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        DirDejarPed1 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped1 = new RSMaterialComponent.RSTextFieldMaterial();
        EstadoPed1 = new RSMaterialComponent.RSComboBoxMaterial();
        SeleccionarCadete1 = new RSMaterialComponent.RSComboBoxMaterial();
        Mas1 = new javax.swing.JLabel();
        menos1 = new javax.swing.JLabel();
        DirRetorarped3 = new RSMaterialComponent.RSTextFieldMaterial();
        DirDejarPed2 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped2 = new RSMaterialComponent.RSTextFieldMaterial();
        EstadoPed2 = new RSMaterialComponent.RSComboBoxMaterial();
        SeleccionarCadete2 = new RSMaterialComponent.RSComboBoxMaterial();
        menos2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DirRetorarped4 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel6 = new javax.swing.JLabel();
        Final_Precio_P = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area_Descripcion_P = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        ingresar_HD_P = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped6 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped7 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped8 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped9 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped10 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped11 = new RSMaterialComponent.RSTextFieldMaterial();
        ingresar_HR_P = new RSMaterialComponent.RSTextFieldMaterial();
        cliente_No_Exite_RP = new javax.swing.JLabel();
        Apellido_RP1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel10 = new javax.swing.JLabel();
        DirRetorarped5 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped12 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped13 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped14 = new RSMaterialComponent.RSTextFieldMaterial();
        fe = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped16 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped17 = new RSMaterialComponent.RSTextFieldMaterial();
        DirRetorarped18 = new RSMaterialComponent.RSTextFieldMaterial();
        ingresar_HD_P1 = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1242, 562));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/Registro_Pedidos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, -1, 50));

        ingresar_DirR_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_DirR_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_DirR_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_DirR_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_DirR_P.setPlaceholder("Ingrese Dir. A retirar Pedido");
        jPanel1.add(ingresar_DirR_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 40));

        ingresar_DirA_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_DirA_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_DirA_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_DirA_P.setPlaceholder("Ingrese Dir. A dejar Pedido");
        jPanel1.add(ingresar_DirA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, 40));

        Domicilio_RP.setForeground(new java.awt.Color(51, 51, 51));
        Domicilio_RP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Domicilio_RP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Domicilio_RP.setPhColor(new java.awt.Color(0, 0, 0));
        Domicilio_RP.setPlaceholder("Domicilio");
        jPanel1.add(Domicilio_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 218, 40));

        Ingrese_telefono_NP.setForeground(new java.awt.Color(51, 51, 51));
        Ingrese_telefono_NP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Ingrese_telefono_NP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Ingrese_telefono_NP.setPhColor(new java.awt.Color(0, 0, 0));
        Ingrese_telefono_NP.setPlaceholder("Ingrese Telefono");
        Ingrese_telefono_NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingrese_telefono_NPActionPerformed(evt);
            }
        });
        jPanel1.add(Ingrese_telefono_NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 150, -1));

        Entrar_btn.setBackground(new java.awt.Color(153, 153, 153));
        Entrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn.setText("Volver");
        Entrar_btn.setContentAreaFilled(false);
        Entrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 232, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/flecha-correcta.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, -1, -1));

        Entrar_btn1.setBackground(new java.awt.Color(102, 102, 255));
        Entrar_btn1.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn1.setText("Registrar");
        Entrar_btn1.setContentAreaFilled(false);
        Entrar_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 580, 232, 50));

        Nombre_RP.setForeground(new java.awt.Color(51, 51, 51));
        Nombre_RP.setColorMaterial(new java.awt.Color(153, 102, 255));
        Nombre_RP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Nombre_RP.setPhColor(new java.awt.Color(0, 0, 0));
        Nombre_RP.setPlaceholder("Ingrese Nombre");
        jPanel1.add(Nombre_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 218, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 81, -1, -1));

        DirRetorarped.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped.setPlaceholder("Fecha R");
        jPanel1.add(DirRetorarped, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 90, 40));

        DirDejarPed.setForeground(new java.awt.Color(51, 51, 51));
        DirDejarPed.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirDejarPed.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirDejarPed.setPhColor(new java.awt.Color(0, 0, 0));
        DirDejarPed.setPlaceholder("Ingrese Dir. A dejar Pedido");
        jPanel1.add(DirDejarPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 140, 40));

        menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/eliminar.png"))); // NOI18N
        menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosMouseClicked(evt);
            }
        });
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 160, -1, -1));

        Mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        Mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasMouseClicked(evt);
            }
        });
        jPanel1.add(Mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 160, -1, -1));

        EstadoPed.setForeground(new java.awt.Color(102, 102, 102));
        EstadoPed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Fragil", "No fragil" }));
        jPanel1.add(EstadoPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, 110, 43));

        ingresar_Estado_P.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Estado_P.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Activo", "En Preparacion" }));
        ingresar_Estado_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_Estado_PActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar_Estado_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 110, 43));

        SeleccionarCadete.setForeground(new java.awt.Color(102, 102, 102));
        SeleccionarCadete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cadete", "Mario", "Pedro", "Julio" }));
        jPanel1.add(SeleccionarCadete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 140, 43));

        ingresar_Cadete_P.setForeground(new java.awt.Color(102, 102, 102));
        ingresar_Cadete_P.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cadete", "1" }));
        jPanel1.add(ingresar_Cadete_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, 140, 43));

        rSButtonMaterialTwo3.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMaterialTwo3.setText("Buscar");
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 80, 50));

        DirDejarPed1.setForeground(new java.awt.Color(51, 51, 51));
        DirDejarPed1.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirDejarPed1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirDejarPed1.setPhColor(new java.awt.Color(0, 0, 0));
        DirDejarPed1.setPlaceholder("Ingrese Dir. A dejar Pedido");
        jPanel1.add(DirDejarPed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, 40));

        DirRetorarped1.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped1.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped1.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped1.setPlaceholder("Ingrese Dir. A retirar Pedido");
        jPanel1.add(DirRetorarped1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 150, 40));

        EstadoPed1.setForeground(new java.awt.Color(102, 102, 102));
        EstadoPed1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Fragil", "No fragil" }));
        jPanel1.add(EstadoPed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 110, 43));

        SeleccionarCadete1.setForeground(new java.awt.Color(102, 102, 102));
        SeleccionarCadete1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cadete", "Mario", "Pedro", "Julio" }));
        jPanel1.add(SeleccionarCadete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, 140, 43));

        Mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/anadir(1).png"))); // NOI18N
        Mas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mas1MouseClicked(evt);
            }
        });
        jPanel1.add(Mas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 220, -1, -1));

        menos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/eliminar.png"))); // NOI18N
        menos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos1MouseClicked(evt);
            }
        });
        jPanel1.add(menos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 220, -1, -1));

        DirRetorarped3.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped3.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped3.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped3.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped3.setPlaceholder("$");
        jPanel1.add(DirRetorarped3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 170, 40));

        DirDejarPed2.setForeground(new java.awt.Color(51, 51, 51));
        DirDejarPed2.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirDejarPed2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirDejarPed2.setPhColor(new java.awt.Color(0, 0, 0));
        DirDejarPed2.setPlaceholder("Ingrese Dir. A dejar Pedido");
        jPanel1.add(DirDejarPed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 140, 40));

        DirRetorarped2.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped2.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped2.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped2.setPlaceholder("Ingrese Dir. A retirar Pedido");
        jPanel1.add(DirRetorarped2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 150, 40));

        EstadoPed2.setForeground(new java.awt.Color(102, 102, 102));
        EstadoPed2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "Fragil", "No fragil" }));
        jPanel1.add(EstadoPed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 110, 43));

        SeleccionarCadete2.setForeground(new java.awt.Color(102, 102, 102));
        SeleccionarCadete2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cadete", "Mario", "Pedro", "Julio" }));
        jPanel1.add(SeleccionarCadete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 140, 43));

        menos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/eliminar.png"))); // NOI18N
        menos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menos2MouseClicked(evt);
            }
        });
        jPanel1.add(menos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Iva");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, -1, -1));

        DirRetorarped4.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped4.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped4.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped4.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped4.setPlaceholder("$");
        jPanel1.add(DirRetorarped4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 420, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Final");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, -1, -1));

        Final_Precio_P.setForeground(new java.awt.Color(51, 51, 51));
        Final_Precio_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        Final_Precio_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Final_Precio_P.setPhColor(new java.awt.Color(0, 0, 0));
        Final_Precio_P.setPlaceholder("$");
        jPanel1.add(Final_Precio_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, 170, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descuento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/Cuadrado4.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 230, 150));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Detalles de Cliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Area_Descripcion_P.setColumns(20);
        Area_Descripcion_P.setRows(5);
        jScrollPane1.setViewportView(Area_Descripcion_P);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 410, 150));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ingrese Descripcion(Opcional)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        ingresar_HD_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_HD_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_HD_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_HD_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_HD_P.setPlaceholder("Hora D.");
        jPanel1.add(ingresar_HD_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 70, 40));

        DirRetorarped6.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped6.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped6.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped6.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped6.setPlaceholder("Hora D.");
        jPanel1.add(DirRetorarped6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 70, 40));

        DirRetorarped7.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped7.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped7.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped7.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped7.setPlaceholder("Hora D.");
        jPanel1.add(DirRetorarped7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 70, 40));

        DirRetorarped8.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped8.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped8.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped8.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped8.setPlaceholder("Hora D.");
        jPanel1.add(DirRetorarped8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 70, 40));

        DirRetorarped9.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped9.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped9.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped9.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped9.setPlaceholder("Hora R.");
        jPanel1.add(DirRetorarped9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 70, 40));

        DirRetorarped10.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped10.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped10.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped10.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped10.setPlaceholder("Hora R.");
        jPanel1.add(DirRetorarped10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 70, 40));

        DirRetorarped11.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped11.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped11.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped11.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped11.setPlaceholder("Hora R.");
        jPanel1.add(DirRetorarped11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 70, 40));

        ingresar_HR_P.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_HR_P.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_HR_P.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_HR_P.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_HR_P.setPlaceholder("Hora R.");
        jPanel1.add(ingresar_HR_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 70, 40));
        jPanel1.add(cliente_No_Exite_RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        Apellido_RP1.setForeground(new java.awt.Color(51, 51, 51));
        Apellido_RP1.setColorMaterial(new java.awt.Color(153, 102, 255));
        Apellido_RP1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        Apellido_RP1.setPhColor(new java.awt.Color(0, 0, 0));
        Apellido_RP1.setPlaceholder("Ingrese Apellido");
        jPanel1.add(Apellido_RP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 218, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Detalle de Pedido");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        DirRetorarped5.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped5.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped5.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped5.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped5.setPlaceholder("Ingrese Dir. A retirar Pedido");
        jPanel1.add(DirRetorarped5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 150, 40));

        DirRetorarped12.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped12.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped12.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped12.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped12.setPlaceholder("Fecha R");
        jPanel1.add(DirRetorarped12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 90, 40));

        DirRetorarped13.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped13.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped13.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped13.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped13.setPlaceholder("Fecha R");
        jPanel1.add(DirRetorarped13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 90, 40));

        DirRetorarped14.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped14.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped14.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped14.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped14.setPlaceholder("Fecha R");
        jPanel1.add(DirRetorarped14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 90, 40));

        fe.setForeground(new java.awt.Color(51, 51, 51));
        fe.setColorMaterial(new java.awt.Color(153, 255, 153));
        fe.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        fe.setPhColor(new java.awt.Color(0, 0, 0));
        fe.setPlaceholder("Fecha D");
        jPanel1.add(fe, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 90, 40));

        DirRetorarped16.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped16.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped16.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped16.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped16.setPlaceholder("Fecha D");
        jPanel1.add(DirRetorarped16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 90, 40));

        DirRetorarped17.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped17.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped17.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped17.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped17.setPlaceholder("Fecha D");
        jPanel1.add(DirRetorarped17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 90, 40));

        DirRetorarped18.setForeground(new java.awt.Color(51, 51, 51));
        DirRetorarped18.setColorMaterial(new java.awt.Color(153, 255, 153));
        DirRetorarped18.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        DirRetorarped18.setPhColor(new java.awt.Color(0, 0, 0));
        DirRetorarped18.setPlaceholder("Fecha D");
        jPanel1.add(DirRetorarped18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 90, 40));

        ingresar_HD_P1.setForeground(new java.awt.Color(51, 51, 51));
        ingresar_HD_P1.setColorMaterial(new java.awt.Color(153, 255, 153));
        ingresar_HD_P1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ingresar_HD_P1.setPhColor(new java.awt.Color(0, 0, 0));
        ingresar_HD_P1.setPlaceholder("Hora D.");
        jPanel1.add(ingresar_HD_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btnActionPerformed
    
        dispose();
    }//GEN-LAST:event_Entrar_btnActionPerformed

    private void Entrar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btn1ActionPerformed
ControlPedido cc = new ControlPedido();
        try {
            cc.insertarPedido(this);
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Pedido_Nuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Entrar_btn1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
          
        DirDejarPed.setVisible(true);
        DirRetorarped.setVisible(true);
        EstadoPed.setVisible(true);
        SeleccionarCadete.setVisible(true);
        Mas.setVisible(true);
        menos.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void MasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasMouseClicked
       
        DirDejarPed1.setVisible(true);
        DirRetorarped1.setVisible(true);
        EstadoPed1.setVisible(true);
        SeleccionarCadete1.setVisible(true);
        Mas1.setVisible(true);
        menos1.setVisible(true);
    }//GEN-LAST:event_MasMouseClicked

    private void ingresar_Estado_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_Estado_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_Estado_PActionPerformed

    private void Mas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mas1MouseClicked
       
        DirDejarPed2.setVisible(true);
        DirRetorarped2.setVisible(true);
        EstadoPed2.setVisible(true);
        SeleccionarCadete2.setVisible(true);
       // Mas2.setVisible(true);
        menos2.setVisible(true);
    }//GEN-LAST:event_Mas1MouseClicked

    private void menos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos2MouseClicked
       
        DirDejarPed2.setVisible(false);
        DirRetorarped2.setVisible(false);
        EstadoPed2.setVisible(false);
        SeleccionarCadete2.setVisible(false);
        //Mas2.setVisible(false);
        menos2.setVisible(false);
    }//GEN-LAST:event_menos2MouseClicked

    private void menos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menos1MouseClicked
        
        DirDejarPed1.setVisible(false);
        DirRetorarped1.setVisible(false);
        EstadoPed1.setVisible(false);
        SeleccionarCadete1.setVisible(false);
        Mas1.setVisible(false);
        menos1.setVisible(false);
    }//GEN-LAST:event_menos1MouseClicked

    private void menosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosMouseClicked

        DirDejarPed.setVisible(false);
        DirRetorarped.setVisible(false);
        EstadoPed.setVisible(false);
        SeleccionarCadete.setVisible(false);
        Mas.setVisible(false);
        menos.setVisible(false);
    }//GEN-LAST:event_menosMouseClicked

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
        ControlPedido VerCli = new ControlPedido();
          VerCli.ValidarClientePNUEVO(this);
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed

    private void Ingrese_telefono_NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingrese_telefono_NPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingrese_telefono_NPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Pedido_Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Pedido_Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTextFieldMaterial Apellido_RP1;
    public javax.swing.JTextArea Area_Descripcion_P;
    public RSMaterialComponent.RSTextFieldMaterial DirDejarPed;
    public RSMaterialComponent.RSTextFieldMaterial DirDejarPed1;
    public RSMaterialComponent.RSTextFieldMaterial DirDejarPed2;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped1;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped10;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped11;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped12;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped13;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped14;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped16;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped17;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped18;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped2;
    private RSMaterialComponent.RSTextFieldMaterial DirRetorarped3;
    private RSMaterialComponent.RSTextFieldMaterial DirRetorarped4;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped5;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped6;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped7;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped8;
    public RSMaterialComponent.RSTextFieldMaterial DirRetorarped9;
    public RSMaterialComponent.RSTextFieldMaterial Domicilio_RP;
    private necesario.MaterialButton Entrar_btn;
    private necesario.MaterialButton Entrar_btn1;
    public RSMaterialComponent.RSComboBoxMaterial EstadoPed;
    public RSMaterialComponent.RSComboBoxMaterial EstadoPed1;
    public RSMaterialComponent.RSComboBoxMaterial EstadoPed2;
    public RSMaterialComponent.RSTextFieldMaterial Final_Precio_P;
    public RSMaterialComponent.RSTextFieldMaterial Ingrese_telefono_NP;
    private javax.swing.JLabel Mas;
    private javax.swing.JLabel Mas1;
    public RSMaterialComponent.RSTextFieldMaterial Nombre_RP;
    public RSMaterialComponent.RSComboBoxMaterial SeleccionarCadete;
    public RSMaterialComponent.RSComboBoxMaterial SeleccionarCadete1;
    public RSMaterialComponent.RSComboBoxMaterial SeleccionarCadete2;
    public static javax.swing.JLabel cliente_No_Exite_RP;
    public RSMaterialComponent.RSTextFieldMaterial fe;
    public RSMaterialComponent.RSComboBoxMaterial ingresar_Cadete_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_DirA_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_DirR_P;
    public RSMaterialComponent.RSComboBoxMaterial ingresar_Estado_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_HD_P;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_HD_P1;
    public RSMaterialComponent.RSTextFieldMaterial ingresar_HR_P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menos;
    private javax.swing.JLabel menos1;
    private javax.swing.JLabel menos2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    // End of variables declaration//GEN-END:variables
}
