/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPaneles;

import Login.*;
import controladores.ControlComida;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import principal.Principal;

/**
 *
 * @author alex1
 */
public class Registro_Comida_Nueva extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Login
     */
    public Registro_Comida_Nueva() {
        initComponents();
          setIconImage(new ImageIcon(getClass().getResource("probar.png")).getImage());
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreComida = new RSMaterialComponent.RSTextFieldMaterial();
        Cerrar_btn = new necesario.MaterialButton();
        Entrar_btn = new necesario.MaterialButton();
        TipoComida = new RSMaterialComponent.RSComboBoxMaterial();
        PrecioComida = new RSMaterialComponent.RSTextFieldMaterial();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDescripcionComida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EstadoComida = new RSMaterialComponent.RSComboBoxMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(281, 692));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_subPaneles/Registro_Notificaciones.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, -1, 50));

        NombreComida.setForeground(new java.awt.Color(51, 51, 51));
        NombreComida.setColorMaterial(new java.awt.Color(153, 102, 255));
        NombreComida.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        NombreComida.setPhColor(new java.awt.Color(0, 0, 0));
        NombreComida.setPlaceholder("Ingrese Nombre Comida");
        jPanel1.add(NombreComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 79, 220, 40));

        Cerrar_btn.setBackground(new java.awt.Color(153, 153, 255));
        Cerrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar_btn.setText("Volver");
        Cerrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 629, 220, 50));

        Entrar_btn.setBackground(new java.awt.Color(51, 51, 51));
        Entrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Entrar_btn.setText("Registrar");
        Entrar_btn.setContentAreaFilled(false);
        Entrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 573, 220, 50));

        TipoComida.setForeground(new java.awt.Color(102, 102, 102));
        TipoComida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo", "Comida", "Bebida", "Postre" }));
        jPanel1.add(TipoComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, -1));

        PrecioComida.setForeground(new java.awt.Color(51, 51, 51));
        PrecioComida.setColorMaterial(new java.awt.Color(153, 102, 255));
        PrecioComida.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        PrecioComida.setPhColor(new java.awt.Color(0, 0, 0));
        PrecioComida.setPlaceholder("$$");
        jPanel1.add(PrecioComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 40));

        AreaDescripcionComida.setColumns(20);
        AreaDescripcionComida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AreaDescripcionComida.setRows(5);
        AreaDescripcionComida.setName(""); // NOI18N
        jScrollPane1.setViewportView(AreaDescripcionComida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 344, 230, 211));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Descripcion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 318, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Precio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        EstadoComida.setForeground(new java.awt.Color(102, 102, 102));
        EstadoComida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado", "En Venta", "No Venta" }));
        jPanel1.add(EstadoComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_btnActionPerformed
     
        this.dispose();
    }//GEN-LAST:event_Cerrar_btnActionPerformed

    private void Entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_btnActionPerformed
     ControlComida x = new ControlComida();
        try {
            x.AgregarComida(this);
        } catch (SQLException ex) {
            Logger.getLogger(Registro_Comida_Nueva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Entrar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Comida_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Comida_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Comida_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Comida_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Comida_Nueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea AreaDescripcionComida;
    private necesario.MaterialButton Cerrar_btn;
    private necesario.MaterialButton Entrar_btn;
    public RSMaterialComponent.RSComboBoxMaterial EstadoComida;
    public RSMaterialComponent.RSTextFieldMaterial NombreComida;
    public RSMaterialComponent.RSTextFieldMaterial PrecioComida;
    public RSMaterialComponent.RSComboBoxMaterial TipoComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
