/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControlCadete;
import controladores.ControlPagoCadete;
import datos.DatosPagoCadete;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import subPaneles.Realizar_Pago;
import subPaneles.Registro_Cadetes;
import static subPaneles.Registro_Pedido_Nuevo_otro.Final_Precio_P1;
import static subPaneles.Registro_Pedido_Nuevo_otro.tabladecomida;

/**
 *
 * @author RojeruSan
 */
public class pnlChat extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlChat() {
        initComponents();
        tabla_pro_cadete.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabla_pro_cadete.getTableHeader().setOpaque(false);
        tabla_pro_cadete.getTableHeader().setBackground(new Color(32, 136, 203));
        tabla_pro_cadete.getTableHeader().setForeground(new Color(255,255,255));
        tabla_pro_cadete.setRowHeight(25);
        
        actualizartablacadetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_pro_cadete = new javax.swing.JTable();
        rSButtonMaterialTwo2 = new RSMaterialComponent.RSButtonMaterialTwo();
        inicio_lbl5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_pro_cadete1 = new javax.swing.JTable();
        rSButtonMaterialTwo4 = new RSMaterialComponent.RSButtonMaterialTwo();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Recurso 14.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        rSButtonMaterialTwo3.setBackground(new java.awt.Color(102, 102, 255));
        rSButtonMaterialTwo3.setText("Realizar Pago del Dia");
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 159, -1));

        tabla_pro_cadete.setBackground(new java.awt.Color(51, 51, 51));
        tabla_pro_cadete.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tabla_pro_cadete.setForeground(new java.awt.Color(255, 255, 255));
        tabla_pro_cadete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod_Cadete", "Nombre ", "Apellido", "Vehiculo", "Sucursal"
            }
        ));
        tabla_pro_cadete.setCellSelectionEnabled(true);
        tabla_pro_cadete.setFillsViewportHeight(true);
        tabla_pro_cadete.setFocusable(false);
        tabla_pro_cadete.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla_pro_cadete.setRowHeight(25);
        tabla_pro_cadete.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabla_pro_cadete.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_pro_cadete);
        tabla_pro_cadete.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1060, 150));

        rSButtonMaterialTwo2.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMaterialTwo2.setText("Añadir nuevo cadete");
        rSButtonMaterialTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo2ActionPerformed(evt);
            }
        });
        add(rSButtonMaterialTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 159, -1));

        inicio_lbl5.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        inicio_lbl5.setForeground(new java.awt.Color(128, 128, 131));
        inicio_lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/flecha-correcta(1).png"))); // NOI18N
        add(inicio_lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 18, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Registro de todos los cadetes de la sucursal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("*Recuerde que el pago a los cadetes se hace automaticamente al finalizar el dia.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, 20));

        tabla_pro_cadete1.setBackground(new java.awt.Color(51, 51, 51));
        tabla_pro_cadete1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tabla_pro_cadete1.setForeground(new java.awt.Color(255, 255, 255));
        tabla_pro_cadete1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod_Cadete", "Cuit", "Nombre ", "Cant Pedido/Dia", "Pago Final/Dia"
            }
        ));
        tabla_pro_cadete1.setCellSelectionEnabled(true);
        tabla_pro_cadete1.setFillsViewportHeight(true);
        tabla_pro_cadete1.setFocusable(false);
        tabla_pro_cadete1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla_pro_cadete1.setRowHeight(25);
        tabla_pro_cadete1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabla_pro_cadete1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabla_pro_cadete1);
        tabla_pro_cadete1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1060, 200));

        rSButtonMaterialTwo4.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonMaterialTwo4.setText("Modificar cadete");
        add(rSButtonMaterialTwo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 159, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Registro de los pagos del dia x Cadete");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo2ActionPerformed
       Registro_Cadetes x = new Registro_Cadetes();
       x.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialTwo2ActionPerformed

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
    obtenerpreciofinal();       
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed
 public static void actualizartablacadetes(){
    ControlCadete t = new ControlCadete();
     ControlPagoCadete z = new ControlPagoCadete();
        try {
            t.actualizarTablaCadete();
            z.actualizarTablaPagoCadete();
        } catch (SQLException ex) {
            Logger.getLogger(pnlChat.class.getName()).log(Level.SEVERE, null, ex);
        }
 
 
 }
 
 public void obtenerpreciofinal() {
    
        //anda bien el contador
        
    int contadorP=tabla_pro_cadete1.getRowCount();
     System.out.println("tiene cantidad de filas:"+contadorP);
    int i = 0;
     String cantidad = "";
    float PrecioTotal = 0 ;
    String Precio="";
    String precioCadete="";
    Float precioC=null;
  
    while(i<contadorP){
                Precio = tabla_pro_cadete1.getValueAt(i, 4).toString();
                float pre = Float.parseFloat(Precio);
                PrecioTotal = PrecioTotal+(pre);
              
        i++;
    }
    
    precioCadete=Float.toString(PrecioTotal);
    String cadetecantidad= Integer.toString(contadorP);
     Realizar_Pago rt= new Realizar_Pago();
     Realizar_Pago.valorPago.setText(precioCadete);
     Realizar_Pago.cantidad_cadetes.setText(cadetecantidad);
     rt.setVisible(true);
     
     
   
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel inicio_lbl5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo4;
    public static javax.swing.JTable tabla_pro_cadete;
    public static javax.swing.JTable tabla_pro_cadete1;
    // End of variables declaration//GEN-END:variables
}
