/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import controladores.ControlPedido;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import subPaneles.Modificar_Pedido;
import subPaneles.Registro_Pedido_Nuevo_otro;
/**
 *
 * @author RojeruSan
 */
public class pnlCollection extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlCollection() {
        initComponents();
        
        TablaPedido_pendiente.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaPedido_pendiente.getTableHeader().setOpaque(false);
        TablaPedido_pendiente.getTableHeader().setBackground(new Color(32, 136, 203));
        TablaPedido_pendiente.getTableHeader().setForeground(new Color(255,255,255));
        TablaPedido_pendiente.setRowHeight(25);
      
        
         actualizartablas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPedido_pendiente = new javax.swing.JTable();
        rSButtonMaterialTwo2 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        inicio_lbl5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablapedido_EnPrep = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablapedido_Enviados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_Img/Recurso 15.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        TablaPedido_pendiente.setBackground(new java.awt.Color(51, 51, 51));
        TablaPedido_pendiente.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TablaPedido_pendiente.setForeground(new java.awt.Color(255, 255, 255));
        TablaPedido_pendiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod_Pedido", "Nombre Emisor", "Nombre Destinatario", "Calle Origen", "Calle Destino", "Estado", "Descripcion"
            }
        ));
        TablaPedido_pendiente.setFillsViewportHeight(true);
        TablaPedido_pendiente.setFocusable(false);
        TablaPedido_pendiente.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaPedido_pendiente.setRowHeight(25);
        TablaPedido_pendiente.setSelectionBackground(new java.awt.Color(232, 57, 95));
        TablaPedido_pendiente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaPedido_pendiente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1059, 140));

        rSButtonMaterialTwo2.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMaterialTwo2.setText("Añadir nuevo pedido");
        rSButtonMaterialTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo2ActionPerformed(evt);
            }
        });
        add(rSButtonMaterialTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 159, -1));

        rSButtonMaterialTwo3.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonMaterialTwo3.setText("Modificar pedido");
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 159, -1));

        inicio_lbl5.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        inicio_lbl5.setForeground(new java.awt.Color(128, 128, 131));
        inicio_lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Home/flecha-correcta(1).png"))); // NOI18N
        add(inicio_lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 18, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("*Registro de todos los pedidos pendientes.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("*Registro de todos los pedidos En Preparacion.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        Tablapedido_EnPrep.setBackground(new java.awt.Color(51, 51, 51));
        Tablapedido_EnPrep.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Tablapedido_EnPrep.setForeground(new java.awt.Color(255, 255, 255));
        Tablapedido_EnPrep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod_Pedido", "Nombre Emisor", "Nombre Destinatario", "Calle Origen", "Calle Destino", "Estado", "Descripcion"
            }
        ));
        Tablapedido_EnPrep.setFillsViewportHeight(true);
        Tablapedido_EnPrep.setFocusable(false);
        Tablapedido_EnPrep.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tablapedido_EnPrep.setRowHeight(25);
        Tablapedido_EnPrep.setSelectionBackground(new java.awt.Color(232, 57, 95));
        Tablapedido_EnPrep.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tablapedido_EnPrep);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1059, 140));

        Tablapedido_Enviados.setBackground(new java.awt.Color(51, 51, 51));
        Tablapedido_Enviados.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Tablapedido_Enviados.setForeground(new java.awt.Color(255, 255, 255));
        Tablapedido_Enviados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod_Pedido", "Nombre Emisor", "Nombre Destinatario", "Calle Origen", "Calle Destino", "Estado", "Descripcion"
            }
        ));
        Tablapedido_Enviados.setFillsViewportHeight(true);
        Tablapedido_Enviados.setFocusable(false);
        Tablapedido_Enviados.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tablapedido_Enviados.setRowHeight(25);
        Tablapedido_Enviados.setSelectionBackground(new java.awt.Color(232, 57, 95));
        Tablapedido_Enviados.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(Tablapedido_Enviados);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1059, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("*Registro de todos los pedidos Enviados.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo2ActionPerformed
      Registro_Pedido_Nuevo_otro x = new Registro_Pedido_Nuevo_otro();
       x.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialTwo2ActionPerformed

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
      Modificar_Pedido x = new Modificar_Pedido();
        x.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed

public void actualizartablas(){

 ControlPedido t = new ControlPedido();
        try {
            t.actualizarTablaPedidosMenuPedidosPendientes();
            t.actualizarTablaPedidosMenuPedidosEnviados();
            t.actualizarTablaPedidosMenuPedidosEnP();
        } catch (SQLException ex) {
            Logger.getLogger(pnlHome.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaPedido_pendiente;
    public static javax.swing.JTable Tablapedido_EnPrep;
    public static javax.swing.JTable Tablapedido_Enviados;
    public javax.swing.JLabel inicio_lbl5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    // End of variables declaration//GEN-END:variables
}
